# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

manifest:
  projects:
    - name: zephyr
      remote: ambiq
      repo-path: zephyr-ambiq-internal
      revision: ambiq-stable
      import:
        # By using name-allowlist we can clone only the modules that are
        # strictly needed by the application.
        name-allowlist:
          - cmsis_6    # required by the ARM port for Cortex-M
          - hal_ambiq # required by the custom_plank board (Ambiq based)
  remotes:
    - name: ambiq
      url-base: https://github.com/AmbiqMicro
